// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockagent

import (
	"context"

	"github.com/google/uuid"
	"github.com/openotters/agentfile/executor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAgent creates a new instance of MockAgent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgent {
	mock := &MockAgent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgent is an autogenerated mock type for the Agent type
type MockAgent struct {
	mock.Mock
}

type MockAgent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgent) EXPECT() *MockAgent_Expecter {
	return &MockAgent_Expecter{mock: &_m.Mock}
}

// Prepare provides a mock function for the type MockAgent
func (_mock *MockAgent) Prepare(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgent_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type MockAgent_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgent_Expecter) Prepare(ctx interface{}) *MockAgent_Prepare_Call {
	return &MockAgent_Prepare_Call{Call: _e.mock.On("Prepare", ctx)}
}

func (_c *MockAgent_Prepare_Call) Run(run func(ctx context.Context)) *MockAgent_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgent_Prepare_Call) Return(err error) *MockAgent_Prepare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgent_Prepare_Call) RunAndReturn(run func(ctx context.Context) error) *MockAgent_Prepare_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockAgent
func (_mock *MockAgent) Remove(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgent_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockAgent_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgent_Expecter) Remove(ctx interface{}) *MockAgent_Remove_Call {
	return &MockAgent_Remove_Call{Call: _e.mock.On("Remove", ctx)}
}

func (_c *MockAgent_Remove_Call) Run(run func(ctx context.Context)) *MockAgent_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgent_Remove_Call) Return(err error) *MockAgent_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgent_Remove_Call) RunAndReturn(run func(ctx context.Context) error) *MockAgent_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockAgent
func (_mock *MockAgent) Run(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgent_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockAgent_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgent_Expecter) Run(ctx interface{}) *MockAgent_Run_Call {
	return &MockAgent_Run_Call{Call: _e.mock.On("Run", ctx)}
}

func (_c *MockAgent_Run_Call) Run(run func(ctx context.Context)) *MockAgent_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgent_Run_Call) Return(err error) *MockAgent_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgent_Run_Call) RunAndReturn(run func(ctx context.Context) error) *MockAgent_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Runtime provides a mock function for the type MockAgent
func (_mock *MockAgent) Runtime() *executor.Runtime {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Runtime")
	}

	var r0 *executor.Runtime
	if returnFunc, ok := ret.Get(0).(func() *executor.Runtime); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*executor.Runtime)
		}
	}
	return r0
}

// MockAgent_Runtime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Runtime'
type MockAgent_Runtime_Call struct {
	*mock.Call
}

// Runtime is a helper method to define mock.On call
func (_e *MockAgent_Expecter) Runtime() *MockAgent_Runtime_Call {
	return &MockAgent_Runtime_Call{Call: _e.mock.On("Runtime")}
}

func (_c *MockAgent_Runtime_Call) Run(run func()) *MockAgent_Runtime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_Runtime_Call) Return(agentRuntime *executor.Runtime) *MockAgent_Runtime_Call {
	_c.Call.Return(agentRuntime)
	return _c
}

func (_c *MockAgent_Runtime_Call) RunAndReturn(run func() *executor.Runtime) *MockAgent_Runtime_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockAgent
func (_mock *MockAgent) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgent_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockAgent_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgent_Expecter) Start(ctx interface{}) *MockAgent_Start_Call {
	return &MockAgent_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockAgent_Start_Call) Run(run func(ctx context.Context)) *MockAgent_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgent_Start_Call) Return(err error) *MockAgent_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgent_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockAgent_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockAgent
func (_mock *MockAgent) Status() executor.Status {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 executor.Status
	if returnFunc, ok := ret.Get(0).(func() executor.Status); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(executor.Status)
	}
	return r0
}

// MockAgent_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockAgent_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockAgent_Expecter) Status() *MockAgent_Status_Call {
	return &MockAgent_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockAgent_Status_Call) Run(run func()) *MockAgent_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_Status_Call) Return(status executor.Status) *MockAgent_Status_Call {
	_c.Call.Return(status)
	return _c
}

func (_c *MockAgent_Status_Call) RunAndReturn(run func() executor.Status) *MockAgent_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockAgent
func (_mock *MockAgent) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgent_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockAgent_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgent_Expecter) Stop(ctx interface{}) *MockAgent_Stop_Call {
	return &MockAgent_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *MockAgent_Stop_Call) Run(run func(ctx context.Context)) *MockAgent_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgent_Stop_Call) Return(err error) *MockAgent_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgent_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *MockAgent_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeStatus provides a mock function for the type MockAgent
func (_mock *MockAgent) SubscribeStatus() (<-chan executor.Status, func()) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SubscribeStatus")
	}

	var r0 <-chan executor.Status
	var r1 func()
	if returnFunc, ok := ret.Get(0).(func() (<-chan executor.Status, func())); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() <-chan executor.Status); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan executor.Status)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() func()); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}
	return r0, r1
}

// MockAgent_SubscribeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeStatus'
type MockAgent_SubscribeStatus_Call struct {
	*mock.Call
}

// SubscribeStatus is a helper method to define mock.On call
func (_e *MockAgent_Expecter) SubscribeStatus() *MockAgent_SubscribeStatus_Call {
	return &MockAgent_SubscribeStatus_Call{Call: _e.mock.On("SubscribeStatus")}
}

func (_c *MockAgent_SubscribeStatus_Call) Run(run func()) *MockAgent_SubscribeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_SubscribeStatus_Call) Return(statusCh <-chan executor.Status, fn func()) *MockAgent_SubscribeStatus_Call {
	_c.Call.Return(statusCh, fn)
	return _c
}

func (_c *MockAgent_SubscribeStatus_Call) RunAndReturn(run func() (<-chan executor.Status, func())) *MockAgent_SubscribeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UUID provides a mock function for the type MockAgent
func (_mock *MockAgent) UUID() uuid.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UUID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockAgent_UUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UUID'
type MockAgent_UUID_Call struct {
	*mock.Call
}

// UUID is a helper method to define mock.On call
func (_e *MockAgent_Expecter) UUID() *MockAgent_UUID_Call {
	return &MockAgent_UUID_Call{Call: _e.mock.On("UUID")}
}

func (_c *MockAgent_UUID_Call) Run(run func()) *MockAgent_UUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAgent_UUID_Call) Return(uUID uuid.UUID) *MockAgent_UUID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockAgent_UUID_Call) RunAndReturn(run func() uuid.UUID) *MockAgent_UUID_Call {
	_c.Call.Return(run)
	return _c
}
