// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockagent

import (
	"context"

	"github.com/google/uuid"
	"github.com/openotters/agentfile/agent"
	"github.com/openotters/agentfile/spec"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockProvider
func (_mock *MockProvider) Create(ctx context.Context, id uuid.UUID, ref spec.Reference, opts ...spec.Override) (agent.Agent, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, id, ref, opts)
	} else {
		tmpRet = _mock.Called(ctx, id, ref)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 agent.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, spec.Reference, ...spec.Override) (agent.Agent, error)); ok {
		return returnFunc(ctx, id, ref, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, spec.Reference, ...spec.Override) agent.Agent); ok {
		r0 = returnFunc(ctx, id, ref, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(agent.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, spec.Reference, ...spec.Override) error); ok {
		r1 = returnFunc(ctx, id, ref, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProvider_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - ref spec.Reference
//   - opts ...spec.Override
func (_e *MockProvider_Expecter) Create(ctx interface{}, id interface{}, ref interface{}, opts ...interface{}) *MockProvider_Create_Call {
	return &MockProvider_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{ctx, id, ref}, opts...)...)}
}

func (_c *MockProvider_Create_Call) Run(run func(ctx context.Context, id uuid.UUID, ref spec.Reference, opts ...spec.Override)) *MockProvider_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 spec.Reference
		if args[2] != nil {
			arg2 = args[2].(spec.Reference)
		}
		var arg3 []spec.Override
		var variadicArgs []spec.Override
		if len(args) > 3 {
			variadicArgs = args[3].([]spec.Override)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockProvider_Create_Call) Return(agent1 agent.Agent, err error) *MockProvider_Create_Call {
	_c.Call.Return(agent1, err)
	return _c
}

func (_c *MockProvider_Create_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, ref spec.Reference, opts ...spec.Override) (agent.Agent, error)) *MockProvider_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function for the type MockProvider
func (_mock *MockProvider) Destroy(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvider_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockProvider_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProvider_Expecter) Destroy(ctx interface{}) *MockProvider_Destroy_Call {
	return &MockProvider_Destroy_Call{Call: _e.mock.On("Destroy", ctx)}
}

func (_c *MockProvider_Destroy_Call) Run(run func(ctx context.Context)) *MockProvider_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProvider_Destroy_Call) Return(err error) *MockProvider_Destroy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvider_Destroy_Call) RunAndReturn(run func(ctx context.Context) error) *MockProvider_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockProvider
func (_mock *MockProvider) Load(ctx context.Context) ([]agent.Agent, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []agent.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]agent.Agent, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []agent.Agent); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]agent.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockProvider_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProvider_Expecter) Load(ctx interface{}) *MockProvider_Load_Call {
	return &MockProvider_Load_Call{Call: _e.mock.On("Load", ctx)}
}

func (_c *MockProvider_Load_Call) Run(run func(ctx context.Context)) *MockProvider_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProvider_Load_Call) Return(agents []agent.Agent, err error) *MockProvider_Load_Call {
	_c.Call.Return(agents, err)
	return _c
}

func (_c *MockProvider_Load_Call) RunAndReturn(run func(ctx context.Context) ([]agent.Agent, error)) *MockProvider_Load_Call {
	_c.Call.Return(run)
	return _c
}
