// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockagent

import (
	"context"

	"github.com/openotters/agentfile/executor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionReader creates a new instance of MockSessionReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionReader {
	mock := &MockSessionReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionReader is an autogenerated mock type for the SessionReader type
type MockSessionReader struct {
	mock.Mock
}

type MockSessionReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionReader) EXPECT() *MockSessionReader_Expecter {
	return &MockSessionReader_Expecter{mock: &_m.Mock}
}

// ListSessionMessages provides a mock function for the type MockSessionReader
func (_mock *MockSessionReader) ListSessionMessages(ctx context.Context, sessionID string, limit int) ([]executor.SessionMessage, error) {
	ret := _mock.Called(ctx, sessionID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListSessionMessages")
	}

	var r0 []executor.SessionMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]executor.SessionMessage, error)); ok {
		return returnFunc(ctx, sessionID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []executor.SessionMessage); ok {
		r0 = returnFunc(ctx, sessionID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]executor.SessionMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, sessionID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionReader_ListSessionMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessionMessages'
type MockSessionReader_ListSessionMessages_Call struct {
	*mock.Call
}

// ListSessionMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - limit int
func (_e *MockSessionReader_Expecter) ListSessionMessages(ctx interface{}, sessionID interface{}, limit interface{}) *MockSessionReader_ListSessionMessages_Call {
	return &MockSessionReader_ListSessionMessages_Call{Call: _e.mock.On("ListSessionMessages", ctx, sessionID, limit)}
}

func (_c *MockSessionReader_ListSessionMessages_Call) Run(run func(ctx context.Context, sessionID string, limit int)) *MockSessionReader_ListSessionMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionReader_ListSessionMessages_Call) Return(sessionMessages []executor.SessionMessage, err error) *MockSessionReader_ListSessionMessages_Call {
	_c.Call.Return(sessionMessages, err)
	return _c
}

func (_c *MockSessionReader_ListSessionMessages_Call) RunAndReturn(run func(ctx context.Context, sessionID string, limit int) ([]executor.SessionMessage, error)) *MockSessionReader_ListSessionMessages_Call {
	_c.Call.Return(run)
	return _c
}
