// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockagent

import (
	"github.com/openotters/agentfile/agent"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStatusObserver creates a new instance of MockStatusObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatusObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatusObserver {
	mock := &MockStatusObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatusObserver is an autogenerated mock type for the StatusObserver type
type MockStatusObserver struct {
	mock.Mock
}

type MockStatusObserver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatusObserver) EXPECT() *MockStatusObserver_Expecter {
	return &MockStatusObserver_Expecter{mock: &_m.Mock}
}

// Status provides a mock function for the type MockStatusObserver
func (_mock *MockStatusObserver) Status() agent.Status {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 agent.Status
	if returnFunc, ok := ret.Get(0).(func() agent.Status); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(agent.Status)
	}
	return r0
}

// MockStatusObserver_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockStatusObserver_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockStatusObserver_Expecter) Status() *MockStatusObserver_Status_Call {
	return &MockStatusObserver_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockStatusObserver_Status_Call) Run(run func()) *MockStatusObserver_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStatusObserver_Status_Call) Return(status agent.Status) *MockStatusObserver_Status_Call {
	_c.Call.Return(status)
	return _c
}

func (_c *MockStatusObserver_Status_Call) RunAndReturn(run func() agent.Status) *MockStatusObserver_Status_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeStatus provides a mock function for the type MockStatusObserver
func (_mock *MockStatusObserver) SubscribeStatus() (<-chan agent.Status, func()) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SubscribeStatus")
	}

	var r0 <-chan agent.Status
	var r1 func()
	if returnFunc, ok := ret.Get(0).(func() (<-chan agent.Status, func())); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() <-chan agent.Status); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan agent.Status)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() func()); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}
	return r0, r1
}

// MockStatusObserver_SubscribeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeStatus'
type MockStatusObserver_SubscribeStatus_Call struct {
	*mock.Call
}

// SubscribeStatus is a helper method to define mock.On call
func (_e *MockStatusObserver_Expecter) SubscribeStatus() *MockStatusObserver_SubscribeStatus_Call {
	return &MockStatusObserver_SubscribeStatus_Call{Call: _e.mock.On("SubscribeStatus")}
}

func (_c *MockStatusObserver_SubscribeStatus_Call) Run(run func()) *MockStatusObserver_SubscribeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStatusObserver_SubscribeStatus_Call) Return(statusCh <-chan agent.Status, fn func()) *MockStatusObserver_SubscribeStatus_Call {
	_c.Call.Return(statusCh, fn)
	return _c
}

func (_c *MockStatusObserver_SubscribeStatus_Call) RunAndReturn(run func() (<-chan agent.Status, func())) *MockStatusObserver_SubscribeStatus_Call {
	_c.Call.Return(run)
	return _c
}
