// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockagent

import (
	"context"

	"github.com/openotters/agentfile/executor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStreamPrompter creates a new instance of MockStreamPrompter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamPrompter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamPrompter {
	mock := &MockStreamPrompter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStreamPrompter is an autogenerated mock type for the StreamPrompter type
type MockStreamPrompter struct {
	mock.Mock
}

type MockStreamPrompter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamPrompter) EXPECT() *MockStreamPrompter_Expecter {
	return &MockStreamPrompter_Expecter{mock: &_m.Mock}
}

// PromptStream provides a mock function for the type MockStreamPrompter
func (_mock *MockStreamPrompter) PromptStream(ctx context.Context, req executor.PromptRequest, cb func(executor.PromptEvent)) error {
	ret := _mock.Called(ctx, req, cb)

	if len(ret) == 0 {
		panic("no return value specified for PromptStream")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, executor.PromptRequest, func(executor.PromptEvent)) error); ok {
		r0 = returnFunc(ctx, req, cb)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStreamPrompter_PromptStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromptStream'
type MockStreamPrompter_PromptStream_Call struct {
	*mock.Call
}

// PromptStream is a helper method to define mock.On call
//   - ctx context.Context
//   - req executor.PromptRequest
//   - cb func(executor.PromptEvent)
func (_e *MockStreamPrompter_Expecter) PromptStream(ctx interface{}, req interface{}, cb interface{}) *MockStreamPrompter_PromptStream_Call {
	return &MockStreamPrompter_PromptStream_Call{Call: _e.mock.On("PromptStream", ctx, req, cb)}
}

func (_c *MockStreamPrompter_PromptStream_Call) Run(run func(ctx context.Context, req executor.PromptRequest, cb func(executor.PromptEvent))) *MockStreamPrompter_PromptStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 executor.PromptRequest
		if args[1] != nil {
			arg1 = args[1].(executor.PromptRequest)
		}
		var arg2 func(executor.PromptEvent)
		if args[2] != nil {
			arg2 = args[2].(func(executor.PromptEvent))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStreamPrompter_PromptStream_Call) Return(err error) *MockStreamPrompter_PromptStream_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStreamPrompter_PromptStream_Call) RunAndReturn(run func(ctx context.Context, req executor.PromptRequest, cb func(executor.PromptEvent)) error) *MockStreamPrompter_PromptStream_Call {
	_c.Call.Return(run)
	return _c
}
