// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: agent/api/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type ChatStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamRequest) Reset() {
	*x = ChatStreamRequest{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamRequest) ProtoMessage() {}

func (x *ChatStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamRequest.ProtoReflect.Descriptor instead.
func (*ChatStreamRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ChatStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatStreamRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type ChatStreamEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Step          int32                  `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	Tool          string                 `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamEvent) Reset() {
	*x = ChatStreamEvent{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamEvent) ProtoMessage() {}

func (x *ChatStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamEvent.ProtoReflect.Descriptor instead.
func (*ChatStreamEvent) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ChatStreamEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatStreamEvent) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *ChatStreamEvent) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ChatStreamEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PromptObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plain-text user prompt (single turn; stateless).
	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Raw JSON Schema bytes. Unmarshalled into fantasy/schema.Schema
	// server-side; the common subset (type, properties, required,
	// items, enum, format, min/max) is supported.
	SchemaJson []byte `protobuf:"bytes,2,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	// Optional — surfaces in tool-mode providers as the synthetic
	// tool's name / description. Ignored otherwise.
	SchemaName    string `protobuf:"bytes,3,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	SchemaDesc    string `protobuf:"bytes,4,opt,name=schema_desc,json=schemaDesc,proto3" json:"schema_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptObjectRequest) Reset() {
	*x = PromptObjectRequest{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptObjectRequest) ProtoMessage() {}

func (x *PromptObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptObjectRequest.ProtoReflect.Descriptor instead.
func (*PromptObjectRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PromptObjectRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *PromptObjectRequest) GetSchemaJson() []byte {
	if x != nil {
		return x.SchemaJson
	}
	return nil
}

func (x *PromptObjectRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *PromptObjectRequest) GetSchemaDesc() string {
	if x != nil {
		return x.SchemaDesc
	}
	return ""
}

type PromptObjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Marshalled structured object (valid JSON bytes).
	ObjectJson []byte `protobuf:"bytes,1,opt,name=object_json,json=objectJson,proto3" json:"object_json,omitempty"`
	// The raw assistant text, mostly useful when the model returned
	// repaired or otherwise interesting content alongside the parse.
	RawText       string `protobuf:"bytes,2,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptObjectResponse) Reset() {
	*x = PromptObjectResponse{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptObjectResponse) ProtoMessage() {}

func (x *PromptObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptObjectResponse.ProtoReflect.Descriptor instead.
func (*PromptObjectResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *PromptObjectResponse) GetObjectJson() []byte {
	if x != nil {
		return x.ObjectJson
	}
	return nil
}

func (x *PromptObjectResponse) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{6}
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageCount  int32                  `protobuf:"varint,2,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	LastActive    int64                  `protobuf:"varint,3,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SessionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionInfo) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SessionInfo) GetLastActive() int64 {
	if x != nil {
		return x.LastActive
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{10}
}

type ListSessionMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 0 = server default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionMessagesRequest) Reset() {
	*x = ListSessionMessagesRequest{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionMessagesRequest) ProtoMessage() {}

func (x *ListSessionMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListSessionMessagesRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ListSessionMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListSessionMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SessionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "user" | "assistant"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessage) Reset() {
	*x = SessionMessage{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessage) ProtoMessage() {}

func (x *SessionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessage.ProtoReflect.Descriptor instead.
func (*SessionMessage) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *SessionMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SessionMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SessionMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListSessionMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*SessionMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionMessagesResponse) Reset() {
	*x = ListSessionMessagesResponse{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionMessagesResponse) ProtoMessage() {}

func (x *ListSessionMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListSessionMessagesResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ListSessionMessagesResponse) GetMessages() []*SessionMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{14}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *HealthResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{16}
}

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

var File_agent_api_v1_agent_proto protoreflect.FileDescriptor

const file_agent_api_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x18agent/api/v1/agent.proto\x12\x13openotters.agent.v1\"D\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\"*\n" +
	"\fChatResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"J\n" +
	"\x11ChatStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\"g\n" +
	"\x0fChatStreamEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04step\x18\x02 \x01(\x05R\x04step\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"\x90\x01\n" +
	"\x13PromptObjectRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1f\n" +
	"\vschema_json\x18\x02 \x01(\fR\n" +
	"schemaJson\x12\x1f\n" +
	"\vschema_name\x18\x03 \x01(\tR\n" +
	"schemaName\x12\x1f\n" +
	"\vschema_desc\x18\x04 \x01(\tR\n" +
	"schemaDesc\"R\n" +
	"\x14PromptObjectResponse\x12\x1f\n" +
	"\vobject_json\x18\x01 \x01(\fR\n" +
	"objectJson\x12\x19\n" +
	"\braw_text\x18\x02 \x01(\tR\arawText\"\x15\n" +
	"\x13ListSessionsRequest\"c\n" +
	"\vSessionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\x05R\fmessageCount\x12\x1f\n" +
	"\vlast_active\x18\x03 \x01(\x03R\n" +
	"lastActive\"T\n" +
	"\x14ListSessionsResponse\x12<\n" +
	"\bsessions\x18\x01 \x03(\v2 .openotters.agent.v1.SessionInfoR\bsessions\"5\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x17\n" +
	"\x15DeleteSessionResponse\"Q\n" +
	"\x1aListSessionMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"]\n" +
	"\x0eSessionMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"^\n" +
	"\x1bListSessionMessagesResponse\x12?\n" +
	"\bmessages\x18\x01 \x03(\v2#.openotters.agent.v1.SessionMessageR\bmessages\"\x0f\n" +
	"\rHealthRequest\"]\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"\x0e\n" +
	"\fReadyRequest\"%\n" +
	"\rReadyResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready2\x88\x06\n" +
	"\fAgentRuntime\x12K\n" +
	"\x04Chat\x12 .openotters.agent.v1.ChatRequest\x1a!.openotters.agent.v1.ChatResponse\x12\\\n" +
	"\n" +
	"ChatStream\x12&.openotters.agent.v1.ChatStreamRequest\x1a$.openotters.agent.v1.ChatStreamEvent0\x01\x12c\n" +
	"\fPromptObject\x12(.openotters.agent.v1.PromptObjectRequest\x1a).openotters.agent.v1.PromptObjectResponse\x12c\n" +
	"\fListSessions\x12(.openotters.agent.v1.ListSessionsRequest\x1a).openotters.agent.v1.ListSessionsResponse\x12f\n" +
	"\rDeleteSession\x12).openotters.agent.v1.DeleteSessionRequest\x1a*.openotters.agent.v1.DeleteSessionResponse\x12x\n" +
	"\x13ListSessionMessages\x12/.openotters.agent.v1.ListSessionMessagesRequest\x1a0.openotters.agent.v1.ListSessionMessagesResponse\x12Q\n" +
	"\x06Health\x12\".openotters.agent.v1.HealthRequest\x1a#.openotters.agent.v1.HealthResponse\x12N\n" +
	"\x05Ready\x12!.openotters.agent.v1.ReadyRequest\x1a\".openotters.agent.v1.ReadyResponseB6Z4github.com/openotters/agentfile/agent/api/v1;agentv1b\x06proto3"

var (
	file_agent_api_v1_agent_proto_rawDescOnce sync.Once
	file_agent_api_v1_agent_proto_rawDescData []byte
)

func file_agent_api_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_api_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_api_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_api_v1_agent_proto_rawDesc), len(file_agent_api_v1_agent_proto_rawDesc)))
	})
	return file_agent_api_v1_agent_proto_rawDescData
}

var file_agent_api_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_agent_api_v1_agent_proto_goTypes = []any{
	(*ChatRequest)(nil),                 // 0: openotters.agent.v1.ChatRequest
	(*ChatResponse)(nil),                // 1: openotters.agent.v1.ChatResponse
	(*ChatStreamRequest)(nil),           // 2: openotters.agent.v1.ChatStreamRequest
	(*ChatStreamEvent)(nil),             // 3: openotters.agent.v1.ChatStreamEvent
	(*PromptObjectRequest)(nil),         // 4: openotters.agent.v1.PromptObjectRequest
	(*PromptObjectResponse)(nil),        // 5: openotters.agent.v1.PromptObjectResponse
	(*ListSessionsRequest)(nil),         // 6: openotters.agent.v1.ListSessionsRequest
	(*SessionInfo)(nil),                 // 7: openotters.agent.v1.SessionInfo
	(*ListSessionsResponse)(nil),        // 8: openotters.agent.v1.ListSessionsResponse
	(*DeleteSessionRequest)(nil),        // 9: openotters.agent.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),       // 10: openotters.agent.v1.DeleteSessionResponse
	(*ListSessionMessagesRequest)(nil),  // 11: openotters.agent.v1.ListSessionMessagesRequest
	(*SessionMessage)(nil),              // 12: openotters.agent.v1.SessionMessage
	(*ListSessionMessagesResponse)(nil), // 13: openotters.agent.v1.ListSessionMessagesResponse
	(*HealthRequest)(nil),               // 14: openotters.agent.v1.HealthRequest
	(*HealthResponse)(nil),              // 15: openotters.agent.v1.HealthResponse
	(*ReadyRequest)(nil),                // 16: openotters.agent.v1.ReadyRequest
	(*ReadyResponse)(nil),               // 17: openotters.agent.v1.ReadyResponse
}
var file_agent_api_v1_agent_proto_depIdxs = []int32{
	7,  // 0: openotters.agent.v1.ListSessionsResponse.sessions:type_name -> openotters.agent.v1.SessionInfo
	12, // 1: openotters.agent.v1.ListSessionMessagesResponse.messages:type_name -> openotters.agent.v1.SessionMessage
	0,  // 2: openotters.agent.v1.AgentRuntime.Chat:input_type -> openotters.agent.v1.ChatRequest
	2,  // 3: openotters.agent.v1.AgentRuntime.ChatStream:input_type -> openotters.agent.v1.ChatStreamRequest
	4,  // 4: openotters.agent.v1.AgentRuntime.PromptObject:input_type -> openotters.agent.v1.PromptObjectRequest
	6,  // 5: openotters.agent.v1.AgentRuntime.ListSessions:input_type -> openotters.agent.v1.ListSessionsRequest
	9,  // 6: openotters.agent.v1.AgentRuntime.DeleteSession:input_type -> openotters.agent.v1.DeleteSessionRequest
	11, // 7: openotters.agent.v1.AgentRuntime.ListSessionMessages:input_type -> openotters.agent.v1.ListSessionMessagesRequest
	14, // 8: openotters.agent.v1.AgentRuntime.Health:input_type -> openotters.agent.v1.HealthRequest
	16, // 9: openotters.agent.v1.AgentRuntime.Ready:input_type -> openotters.agent.v1.ReadyRequest
	1,  // 10: openotters.agent.v1.AgentRuntime.Chat:output_type -> openotters.agent.v1.ChatResponse
	3,  // 11: openotters.agent.v1.AgentRuntime.ChatStream:output_type -> openotters.agent.v1.ChatStreamEvent
	5,  // 12: openotters.agent.v1.AgentRuntime.PromptObject:output_type -> openotters.agent.v1.PromptObjectResponse
	8,  // 13: openotters.agent.v1.AgentRuntime.ListSessions:output_type -> openotters.agent.v1.ListSessionsResponse
	10, // 14: openotters.agent.v1.AgentRuntime.DeleteSession:output_type -> openotters.agent.v1.DeleteSessionResponse
	13, // 15: openotters.agent.v1.AgentRuntime.ListSessionMessages:output_type -> openotters.agent.v1.ListSessionMessagesResponse
	15, // 16: openotters.agent.v1.AgentRuntime.Health:output_type -> openotters.agent.v1.HealthResponse
	17, // 17: openotters.agent.v1.AgentRuntime.Ready:output_type -> openotters.agent.v1.ReadyResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_agent_api_v1_agent_proto_init() }
func file_agent_api_v1_agent_proto_init() {
	if File_agent_api_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_api_v1_agent_proto_rawDesc), len(file_agent_api_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_api_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_api_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_api_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_api_v1_agent_proto = out.File
	file_agent_api_v1_agent_proto_goTypes = nil
	file_agent_api_v1_agent_proto_depIdxs = nil
}
