// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockdocker

import (
	"context"
	"io"

	"github.com/moby/moby/client"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(err error) *MockClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerAttach provides a mock function for the type MockClient
func (_mock *MockClient) ContainerAttach(ctx context.Context, id string, opts client.ContainerAttachOptions) (client.ContainerAttachResult, error) {
	ret := _mock.Called(ctx, id, opts)

	if len(ret) == 0 {
		panic("no return value specified for ContainerAttach")
	}

	var r0 client.ContainerAttachResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerAttachOptions) (client.ContainerAttachResult, error)); ok {
		return returnFunc(ctx, id, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerAttachOptions) client.ContainerAttachResult); ok {
		r0 = returnFunc(ctx, id, opts)
	} else {
		r0 = ret.Get(0).(client.ContainerAttachResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerAttachOptions) error); ok {
		r1 = returnFunc(ctx, id, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ContainerAttach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerAttach'
type MockClient_ContainerAttach_Call struct {
	*mock.Call
}

// ContainerAttach is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - opts client.ContainerAttachOptions
func (_e *MockClient_Expecter) ContainerAttach(ctx interface{}, id interface{}, opts interface{}) *MockClient_ContainerAttach_Call {
	return &MockClient_ContainerAttach_Call{Call: _e.mock.On("ContainerAttach", ctx, id, opts)}
}

func (_c *MockClient_ContainerAttach_Call) Run(run func(ctx context.Context, id string, opts client.ContainerAttachOptions)) *MockClient_ContainerAttach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerAttachOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerAttachOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ContainerAttach_Call) Return(containerAttachResult client.ContainerAttachResult, err error) *MockClient_ContainerAttach_Call {
	_c.Call.Return(containerAttachResult, err)
	return _c
}

func (_c *MockClient_ContainerAttach_Call) RunAndReturn(run func(ctx context.Context, id string, opts client.ContainerAttachOptions) (client.ContainerAttachResult, error)) *MockClient_ContainerAttach_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerCreate provides a mock function for the type MockClient
func (_mock *MockClient) ContainerCreate(ctx context.Context, opts client.ContainerCreateOptions) (client.ContainerCreateResult, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ContainerCreate")
	}

	var r0 client.ContainerCreateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ContainerCreateOptions) (client.ContainerCreateResult, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ContainerCreateOptions) client.ContainerCreateResult); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Get(0).(client.ContainerCreateResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.ContainerCreateOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ContainerCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerCreate'
type MockClient_ContainerCreate_Call struct {
	*mock.Call
}

// ContainerCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - opts client.ContainerCreateOptions
func (_e *MockClient_Expecter) ContainerCreate(ctx interface{}, opts interface{}) *MockClient_ContainerCreate_Call {
	return &MockClient_ContainerCreate_Call{Call: _e.mock.On("ContainerCreate", ctx, opts)}
}

func (_c *MockClient_ContainerCreate_Call) Run(run func(ctx context.Context, opts client.ContainerCreateOptions)) *MockClient_ContainerCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.ContainerCreateOptions
		if args[1] != nil {
			arg1 = args[1].(client.ContainerCreateOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ContainerCreate_Call) Return(containerCreateResult client.ContainerCreateResult, err error) *MockClient_ContainerCreate_Call {
	_c.Call.Return(containerCreateResult, err)
	return _c
}

func (_c *MockClient_ContainerCreate_Call) RunAndReturn(run func(ctx context.Context, opts client.ContainerCreateOptions) (client.ContainerCreateResult, error)) *MockClient_ContainerCreate_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerInspect provides a mock function for the type MockClient
func (_mock *MockClient) ContainerInspect(ctx context.Context, id string, opts client.ContainerInspectOptions) (client.ContainerInspectResult, error) {
	ret := _mock.Called(ctx, id, opts)

	if len(ret) == 0 {
		panic("no return value specified for ContainerInspect")
	}

	var r0 client.ContainerInspectResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerInspectOptions) (client.ContainerInspectResult, error)); ok {
		return returnFunc(ctx, id, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerInspectOptions) client.ContainerInspectResult); ok {
		r0 = returnFunc(ctx, id, opts)
	} else {
		r0 = ret.Get(0).(client.ContainerInspectResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerInspectOptions) error); ok {
		r1 = returnFunc(ctx, id, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ContainerInspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerInspect'
type MockClient_ContainerInspect_Call struct {
	*mock.Call
}

// ContainerInspect is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - opts client.ContainerInspectOptions
func (_e *MockClient_Expecter) ContainerInspect(ctx interface{}, id interface{}, opts interface{}) *MockClient_ContainerInspect_Call {
	return &MockClient_ContainerInspect_Call{Call: _e.mock.On("ContainerInspect", ctx, id, opts)}
}

func (_c *MockClient_ContainerInspect_Call) Run(run func(ctx context.Context, id string, opts client.ContainerInspectOptions)) *MockClient_ContainerInspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerInspectOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerInspectOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ContainerInspect_Call) Return(containerInspectResult client.ContainerInspectResult, err error) *MockClient_ContainerInspect_Call {
	_c.Call.Return(containerInspectResult, err)
	return _c
}

func (_c *MockClient_ContainerInspect_Call) RunAndReturn(run func(ctx context.Context, id string, opts client.ContainerInspectOptions) (client.ContainerInspectResult, error)) *MockClient_ContainerInspect_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerList provides a mock function for the type MockClient
func (_mock *MockClient) ContainerList(ctx context.Context, opts client.ContainerListOptions) (client.ContainerListResult, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ContainerList")
	}

	var r0 client.ContainerListResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ContainerListOptions) (client.ContainerListResult, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ContainerListOptions) client.ContainerListResult); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Get(0).(client.ContainerListResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.ContainerListOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ContainerList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerList'
type MockClient_ContainerList_Call struct {
	*mock.Call
}

// ContainerList is a helper method to define mock.On call
//   - ctx context.Context
//   - opts client.ContainerListOptions
func (_e *MockClient_Expecter) ContainerList(ctx interface{}, opts interface{}) *MockClient_ContainerList_Call {
	return &MockClient_ContainerList_Call{Call: _e.mock.On("ContainerList", ctx, opts)}
}

func (_c *MockClient_ContainerList_Call) Run(run func(ctx context.Context, opts client.ContainerListOptions)) *MockClient_ContainerList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.ContainerListOptions
		if args[1] != nil {
			arg1 = args[1].(client.ContainerListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ContainerList_Call) Return(containerListResult client.ContainerListResult, err error) *MockClient_ContainerList_Call {
	_c.Call.Return(containerListResult, err)
	return _c
}

func (_c *MockClient_ContainerList_Call) RunAndReturn(run func(ctx context.Context, opts client.ContainerListOptions) (client.ContainerListResult, error)) *MockClient_ContainerList_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerLogs provides a mock function for the type MockClient
func (_mock *MockClient) ContainerLogs(ctx context.Context, id string, opts client.ContainerLogsOptions) (client.ContainerLogsResult, error) {
	ret := _mock.Called(ctx, id, opts)

	if len(ret) == 0 {
		panic("no return value specified for ContainerLogs")
	}

	var r0 client.ContainerLogsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerLogsOptions) (client.ContainerLogsResult, error)); ok {
		return returnFunc(ctx, id, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerLogsOptions) client.ContainerLogsResult); ok {
		r0 = returnFunc(ctx, id, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ContainerLogsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerLogsOptions) error); ok {
		r1 = returnFunc(ctx, id, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ContainerLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerLogs'
type MockClient_ContainerLogs_Call struct {
	*mock.Call
}

// ContainerLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - opts client.ContainerLogsOptions
func (_e *MockClient_Expecter) ContainerLogs(ctx interface{}, id interface{}, opts interface{}) *MockClient_ContainerLogs_Call {
	return &MockClient_ContainerLogs_Call{Call: _e.mock.On("ContainerLogs", ctx, id, opts)}
}

func (_c *MockClient_ContainerLogs_Call) Run(run func(ctx context.Context, id string, opts client.ContainerLogsOptions)) *MockClient_ContainerLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerLogsOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerLogsOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ContainerLogs_Call) Return(containerLogsResult client.ContainerLogsResult, err error) *MockClient_ContainerLogs_Call {
	_c.Call.Return(containerLogsResult, err)
	return _c
}

func (_c *MockClient_ContainerLogs_Call) RunAndReturn(run func(ctx context.Context, id string, opts client.ContainerLogsOptions) (client.ContainerLogsResult, error)) *MockClient_ContainerLogs_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerRemove provides a mock function for the type MockClient
func (_mock *MockClient) ContainerRemove(ctx context.Context, id string, opts client.ContainerRemoveOptions) (client.ContainerRemoveResult, error) {
	ret := _mock.Called(ctx, id, opts)

	if len(ret) == 0 {
		panic("no return value specified for ContainerRemove")
	}

	var r0 client.ContainerRemoveResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerRemoveOptions) (client.ContainerRemoveResult, error)); ok {
		return returnFunc(ctx, id, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerRemoveOptions) client.ContainerRemoveResult); ok {
		r0 = returnFunc(ctx, id, opts)
	} else {
		r0 = ret.Get(0).(client.ContainerRemoveResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerRemoveOptions) error); ok {
		r1 = returnFunc(ctx, id, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ContainerRemove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerRemove'
type MockClient_ContainerRemove_Call struct {
	*mock.Call
}

// ContainerRemove is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - opts client.ContainerRemoveOptions
func (_e *MockClient_Expecter) ContainerRemove(ctx interface{}, id interface{}, opts interface{}) *MockClient_ContainerRemove_Call {
	return &MockClient_ContainerRemove_Call{Call: _e.mock.On("ContainerRemove", ctx, id, opts)}
}

func (_c *MockClient_ContainerRemove_Call) Run(run func(ctx context.Context, id string, opts client.ContainerRemoveOptions)) *MockClient_ContainerRemove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerRemoveOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerRemoveOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ContainerRemove_Call) Return(containerRemoveResult client.ContainerRemoveResult, err error) *MockClient_ContainerRemove_Call {
	_c.Call.Return(containerRemoveResult, err)
	return _c
}

func (_c *MockClient_ContainerRemove_Call) RunAndReturn(run func(ctx context.Context, id string, opts client.ContainerRemoveOptions) (client.ContainerRemoveResult, error)) *MockClient_ContainerRemove_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerStart provides a mock function for the type MockClient
func (_mock *MockClient) ContainerStart(ctx context.Context, id string, opts client.ContainerStartOptions) (client.ContainerStartResult, error) {
	ret := _mock.Called(ctx, id, opts)

	if len(ret) == 0 {
		panic("no return value specified for ContainerStart")
	}

	var r0 client.ContainerStartResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerStartOptions) (client.ContainerStartResult, error)); ok {
		return returnFunc(ctx, id, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerStartOptions) client.ContainerStartResult); ok {
		r0 = returnFunc(ctx, id, opts)
	} else {
		r0 = ret.Get(0).(client.ContainerStartResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerStartOptions) error); ok {
		r1 = returnFunc(ctx, id, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ContainerStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStart'
type MockClient_ContainerStart_Call struct {
	*mock.Call
}

// ContainerStart is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - opts client.ContainerStartOptions
func (_e *MockClient_Expecter) ContainerStart(ctx interface{}, id interface{}, opts interface{}) *MockClient_ContainerStart_Call {
	return &MockClient_ContainerStart_Call{Call: _e.mock.On("ContainerStart", ctx, id, opts)}
}

func (_c *MockClient_ContainerStart_Call) Run(run func(ctx context.Context, id string, opts client.ContainerStartOptions)) *MockClient_ContainerStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerStartOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerStartOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ContainerStart_Call) Return(containerStartResult client.ContainerStartResult, err error) *MockClient_ContainerStart_Call {
	_c.Call.Return(containerStartResult, err)
	return _c
}

func (_c *MockClient_ContainerStart_Call) RunAndReturn(run func(ctx context.Context, id string, opts client.ContainerStartOptions) (client.ContainerStartResult, error)) *MockClient_ContainerStart_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerStop provides a mock function for the type MockClient
func (_mock *MockClient) ContainerStop(ctx context.Context, id string, opts client.ContainerStopOptions) (client.ContainerStopResult, error) {
	ret := _mock.Called(ctx, id, opts)

	if len(ret) == 0 {
		panic("no return value specified for ContainerStop")
	}

	var r0 client.ContainerStopResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerStopOptions) (client.ContainerStopResult, error)); ok {
		return returnFunc(ctx, id, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ContainerStopOptions) client.ContainerStopResult); ok {
		r0 = returnFunc(ctx, id, opts)
	} else {
		r0 = ret.Get(0).(client.ContainerStopResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ContainerStopOptions) error); ok {
		r1 = returnFunc(ctx, id, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ContainerStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStop'
type MockClient_ContainerStop_Call struct {
	*mock.Call
}

// ContainerStop is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - opts client.ContainerStopOptions
func (_e *MockClient_Expecter) ContainerStop(ctx interface{}, id interface{}, opts interface{}) *MockClient_ContainerStop_Call {
	return &MockClient_ContainerStop_Call{Call: _e.mock.On("ContainerStop", ctx, id, opts)}
}

func (_c *MockClient_ContainerStop_Call) Run(run func(ctx context.Context, id string, opts client.ContainerStopOptions)) *MockClient_ContainerStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ContainerStopOptions
		if args[2] != nil {
			arg2 = args[2].(client.ContainerStopOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ContainerStop_Call) Return(containerStopResult client.ContainerStopResult, err error) *MockClient_ContainerStop_Call {
	_c.Call.Return(containerStopResult, err)
	return _c
}

func (_c *MockClient_ContainerStop_Call) RunAndReturn(run func(ctx context.Context, id string, opts client.ContainerStopOptions) (client.ContainerStopResult, error)) *MockClient_ContainerStop_Call {
	_c.Call.Return(run)
	return _c
}

// ImageInspect provides a mock function for the type MockClient
func (_mock *MockClient) ImageInspect(ctx context.Context, imageID string, opts ...client.ImageInspectOption) (client.ImageInspectResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, imageID, opts)
	} else {
		tmpRet = _mock.Called(ctx, imageID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ImageInspect")
	}

	var r0 client.ImageInspectResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.ImageInspectOption) (client.ImageInspectResult, error)); ok {
		return returnFunc(ctx, imageID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.ImageInspectOption) client.ImageInspectResult); ok {
		r0 = returnFunc(ctx, imageID, opts...)
	} else {
		r0 = ret.Get(0).(client.ImageInspectResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...client.ImageInspectOption) error); ok {
		r1 = returnFunc(ctx, imageID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ImageInspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageInspect'
type MockClient_ImageInspect_Call struct {
	*mock.Call
}

// ImageInspect is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID string
//   - opts ...client.ImageInspectOption
func (_e *MockClient_Expecter) ImageInspect(ctx interface{}, imageID interface{}, opts ...interface{}) *MockClient_ImageInspect_Call {
	return &MockClient_ImageInspect_Call{Call: _e.mock.On("ImageInspect",
		append([]interface{}{ctx, imageID}, opts...)...)}
}

func (_c *MockClient_ImageInspect_Call) Run(run func(ctx context.Context, imageID string, opts ...client.ImageInspectOption)) *MockClient_ImageInspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.ImageInspectOption
		var variadicArgs []client.ImageInspectOption
		if len(args) > 2 {
			variadicArgs = args[2].([]client.ImageInspectOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_ImageInspect_Call) Return(imageInspectResult client.ImageInspectResult, err error) *MockClient_ImageInspect_Call {
	_c.Call.Return(imageInspectResult, err)
	return _c
}

func (_c *MockClient_ImageInspect_Call) RunAndReturn(run func(ctx context.Context, imageID string, opts ...client.ImageInspectOption) (client.ImageInspectResult, error)) *MockClient_ImageInspect_Call {
	_c.Call.Return(run)
	return _c
}

// ImageList provides a mock function for the type MockClient
func (_mock *MockClient) ImageList(ctx context.Context, opts client.ImageListOptions) (client.ImageListResult, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ImageList")
	}

	var r0 client.ImageListResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ImageListOptions) (client.ImageListResult, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ImageListOptions) client.ImageListResult); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Get(0).(client.ImageListResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.ImageListOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ImageList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageList'
type MockClient_ImageList_Call struct {
	*mock.Call
}

// ImageList is a helper method to define mock.On call
//   - ctx context.Context
//   - opts client.ImageListOptions
func (_e *MockClient_Expecter) ImageList(ctx interface{}, opts interface{}) *MockClient_ImageList_Call {
	return &MockClient_ImageList_Call{Call: _e.mock.On("ImageList", ctx, opts)}
}

func (_c *MockClient_ImageList_Call) Run(run func(ctx context.Context, opts client.ImageListOptions)) *MockClient_ImageList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.ImageListOptions
		if args[1] != nil {
			arg1 = args[1].(client.ImageListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ImageList_Call) Return(imageListResult client.ImageListResult, err error) *MockClient_ImageList_Call {
	_c.Call.Return(imageListResult, err)
	return _c
}

func (_c *MockClient_ImageList_Call) RunAndReturn(run func(ctx context.Context, opts client.ImageListOptions) (client.ImageListResult, error)) *MockClient_ImageList_Call {
	_c.Call.Return(run)
	return _c
}

// ImageLoad provides a mock function for the type MockClient
func (_mock *MockClient) ImageLoad(ctx context.Context, input io.Reader, opts ...client.ImageLoadOption) (client.ImageLoadResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ImageLoad")
	}

	var r0 client.ImageLoadResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, ...client.ImageLoadOption) (client.ImageLoadResult, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, ...client.ImageLoadOption) client.ImageLoadResult); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ImageLoadResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, ...client.ImageLoadOption) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ImageLoad_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageLoad'
type MockClient_ImageLoad_Call struct {
	*mock.Call
}

// ImageLoad is a helper method to define mock.On call
//   - ctx context.Context
//   - input io.Reader
//   - opts ...client.ImageLoadOption
func (_e *MockClient_Expecter) ImageLoad(ctx interface{}, input interface{}, opts ...interface{}) *MockClient_ImageLoad_Call {
	return &MockClient_ImageLoad_Call{Call: _e.mock.On("ImageLoad",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *MockClient_ImageLoad_Call) Run(run func(ctx context.Context, input io.Reader, opts ...client.ImageLoadOption)) *MockClient_ImageLoad_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 []client.ImageLoadOption
		var variadicArgs []client.ImageLoadOption
		if len(args) > 2 {
			variadicArgs = args[2].([]client.ImageLoadOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_ImageLoad_Call) Return(imageLoadResult client.ImageLoadResult, err error) *MockClient_ImageLoad_Call {
	_c.Call.Return(imageLoadResult, err)
	return _c
}

func (_c *MockClient_ImageLoad_Call) RunAndReturn(run func(ctx context.Context, input io.Reader, opts ...client.ImageLoadOption) (client.ImageLoadResult, error)) *MockClient_ImageLoad_Call {
	_c.Call.Return(run)
	return _c
}

// ImagePull provides a mock function for the type MockClient
func (_mock *MockClient) ImagePull(ctx context.Context, ref string, opts client.ImagePullOptions) (client.ImagePullResponse, error) {
	ret := _mock.Called(ctx, ref, opts)

	if len(ret) == 0 {
		panic("no return value specified for ImagePull")
	}

	var r0 client.ImagePullResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ImagePullOptions) (client.ImagePullResponse, error)); ok {
		return returnFunc(ctx, ref, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ImagePullOptions) client.ImagePullResponse); ok {
		r0 = returnFunc(ctx, ref, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ImagePullResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ImagePullOptions) error); ok {
		r1 = returnFunc(ctx, ref, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ImagePull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImagePull'
type MockClient_ImagePull_Call struct {
	*mock.Call
}

// ImagePull is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
//   - opts client.ImagePullOptions
func (_e *MockClient_Expecter) ImagePull(ctx interface{}, ref interface{}, opts interface{}) *MockClient_ImagePull_Call {
	return &MockClient_ImagePull_Call{Call: _e.mock.On("ImagePull", ctx, ref, opts)}
}

func (_c *MockClient_ImagePull_Call) Run(run func(ctx context.Context, ref string, opts client.ImagePullOptions)) *MockClient_ImagePull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ImagePullOptions
		if args[2] != nil {
			arg2 = args[2].(client.ImagePullOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ImagePull_Call) Return(imagePullResponse client.ImagePullResponse, err error) *MockClient_ImagePull_Call {
	_c.Call.Return(imagePullResponse, err)
	return _c
}

func (_c *MockClient_ImagePull_Call) RunAndReturn(run func(ctx context.Context, ref string, opts client.ImagePullOptions) (client.ImagePullResponse, error)) *MockClient_ImagePull_Call {
	_c.Call.Return(run)
	return _c
}

// ImagePush provides a mock function for the type MockClient
func (_mock *MockClient) ImagePush(ctx context.Context, ref string, opts client.ImagePushOptions) (client.ImagePushResponse, error) {
	ret := _mock.Called(ctx, ref, opts)

	if len(ret) == 0 {
		panic("no return value specified for ImagePush")
	}

	var r0 client.ImagePushResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ImagePushOptions) (client.ImagePushResponse, error)); ok {
		return returnFunc(ctx, ref, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ImagePushOptions) client.ImagePushResponse); ok {
		r0 = returnFunc(ctx, ref, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ImagePushResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ImagePushOptions) error); ok {
		r1 = returnFunc(ctx, ref, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ImagePush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImagePush'
type MockClient_ImagePush_Call struct {
	*mock.Call
}

// ImagePush is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
//   - opts client.ImagePushOptions
func (_e *MockClient_Expecter) ImagePush(ctx interface{}, ref interface{}, opts interface{}) *MockClient_ImagePush_Call {
	return &MockClient_ImagePush_Call{Call: _e.mock.On("ImagePush", ctx, ref, opts)}
}

func (_c *MockClient_ImagePush_Call) Run(run func(ctx context.Context, ref string, opts client.ImagePushOptions)) *MockClient_ImagePush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ImagePushOptions
		if args[2] != nil {
			arg2 = args[2].(client.ImagePushOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ImagePush_Call) Return(imagePushResponse client.ImagePushResponse, err error) *MockClient_ImagePush_Call {
	_c.Call.Return(imagePushResponse, err)
	return _c
}

func (_c *MockClient_ImagePush_Call) RunAndReturn(run func(ctx context.Context, ref string, opts client.ImagePushOptions) (client.ImagePushResponse, error)) *MockClient_ImagePush_Call {
	_c.Call.Return(run)
	return _c
}

// ImageRemove provides a mock function for the type MockClient
func (_mock *MockClient) ImageRemove(ctx context.Context, imageID string, opts client.ImageRemoveOptions) (client.ImageRemoveResult, error) {
	ret := _mock.Called(ctx, imageID, opts)

	if len(ret) == 0 {
		panic("no return value specified for ImageRemove")
	}

	var r0 client.ImageRemoveResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ImageRemoveOptions) (client.ImageRemoveResult, error)); ok {
		return returnFunc(ctx, imageID, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, client.ImageRemoveOptions) client.ImageRemoveResult); ok {
		r0 = returnFunc(ctx, imageID, opts)
	} else {
		r0 = ret.Get(0).(client.ImageRemoveResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, client.ImageRemoveOptions) error); ok {
		r1 = returnFunc(ctx, imageID, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ImageRemove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageRemove'
type MockClient_ImageRemove_Call struct {
	*mock.Call
}

// ImageRemove is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID string
//   - opts client.ImageRemoveOptions
func (_e *MockClient_Expecter) ImageRemove(ctx interface{}, imageID interface{}, opts interface{}) *MockClient_ImageRemove_Call {
	return &MockClient_ImageRemove_Call{Call: _e.mock.On("ImageRemove", ctx, imageID, opts)}
}

func (_c *MockClient_ImageRemove_Call) Run(run func(ctx context.Context, imageID string, opts client.ImageRemoveOptions)) *MockClient_ImageRemove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 client.ImageRemoveOptions
		if args[2] != nil {
			arg2 = args[2].(client.ImageRemoveOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_ImageRemove_Call) Return(imageRemoveResult client.ImageRemoveResult, err error) *MockClient_ImageRemove_Call {
	_c.Call.Return(imageRemoveResult, err)
	return _c
}

func (_c *MockClient_ImageRemove_Call) RunAndReturn(run func(ctx context.Context, imageID string, opts client.ImageRemoveOptions) (client.ImageRemoveResult, error)) *MockClient_ImageRemove_Call {
	_c.Call.Return(run)
	return _c
}

// ImageSave provides a mock function for the type MockClient
func (_mock *MockClient) ImageSave(ctx context.Context, imageIDs []string, opts ...client.ImageSaveOption) (client.ImageSaveResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, imageIDs, opts)
	} else {
		tmpRet = _mock.Called(ctx, imageIDs)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ImageSave")
	}

	var r0 client.ImageSaveResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ...client.ImageSaveOption) (client.ImageSaveResult, error)); ok {
		return returnFunc(ctx, imageIDs, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ...client.ImageSaveOption) client.ImageSaveResult); ok {
		r0 = returnFunc(ctx, imageIDs, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.ImageSaveResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, ...client.ImageSaveOption) error); ok {
		r1 = returnFunc(ctx, imageIDs, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ImageSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageSave'
type MockClient_ImageSave_Call struct {
	*mock.Call
}

// ImageSave is a helper method to define mock.On call
//   - ctx context.Context
//   - imageIDs []string
//   - opts ...client.ImageSaveOption
func (_e *MockClient_Expecter) ImageSave(ctx interface{}, imageIDs interface{}, opts ...interface{}) *MockClient_ImageSave_Call {
	return &MockClient_ImageSave_Call{Call: _e.mock.On("ImageSave",
		append([]interface{}{ctx, imageIDs}, opts...)...)}
}

func (_c *MockClient_ImageSave_Call) Run(run func(ctx context.Context, imageIDs []string, opts ...client.ImageSaveOption)) *MockClient_ImageSave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []client.ImageSaveOption
		var variadicArgs []client.ImageSaveOption
		if len(args) > 2 {
			variadicArgs = args[2].([]client.ImageSaveOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_ImageSave_Call) Return(imageSaveResult client.ImageSaveResult, err error) *MockClient_ImageSave_Call {
	_c.Call.Return(imageSaveResult, err)
	return _c
}

func (_c *MockClient_ImageSave_Call) RunAndReturn(run func(ctx context.Context, imageIDs []string, opts ...client.ImageSaveOption) (client.ImageSaveResult, error)) *MockClient_ImageSave_Call {
	_c.Call.Return(run)
	return _c
}

// ImageTag provides a mock function for the type MockClient
func (_mock *MockClient) ImageTag(ctx context.Context, opts client.ImageTagOptions) (client.ImageTagResult, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ImageTag")
	}

	var r0 client.ImageTagResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ImageTagOptions) (client.ImageTagResult, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ImageTagOptions) client.ImageTagResult); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Get(0).(client.ImageTagResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.ImageTagOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ImageTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImageTag'
type MockClient_ImageTag_Call struct {
	*mock.Call
}

// ImageTag is a helper method to define mock.On call
//   - ctx context.Context
//   - opts client.ImageTagOptions
func (_e *MockClient_Expecter) ImageTag(ctx interface{}, opts interface{}) *MockClient_ImageTag_Call {
	return &MockClient_ImageTag_Call{Call: _e.mock.On("ImageTag", ctx, opts)}
}

func (_c *MockClient_ImageTag_Call) Run(run func(ctx context.Context, opts client.ImageTagOptions)) *MockClient_ImageTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.ImageTagOptions
		if args[1] != nil {
			arg1 = args[1].(client.ImageTagOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ImageTag_Call) Return(imageTagResult client.ImageTagResult, err error) *MockClient_ImageTag_Call {
	_c.Call.Return(imageTagResult, err)
	return _c
}

func (_c *MockClient_ImageTag_Call) RunAndReturn(run func(ctx context.Context, opts client.ImageTagOptions) (client.ImageTagResult, error)) *MockClient_ImageTag_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function for the type MockClient
func (_mock *MockClient) Info(ctx context.Context, opts client.InfoOptions) (client.SystemInfoResult, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 client.SystemInfoResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.InfoOptions) (client.SystemInfoResult, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.InfoOptions) client.SystemInfoResult); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Get(0).(client.SystemInfoResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.InfoOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockClient_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - ctx context.Context
//   - opts client.InfoOptions
func (_e *MockClient_Expecter) Info(ctx interface{}, opts interface{}) *MockClient_Info_Call {
	return &MockClient_Info_Call{Call: _e.mock.On("Info", ctx, opts)}
}

func (_c *MockClient_Info_Call) Run(run func(ctx context.Context, opts client.InfoOptions)) *MockClient_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.InfoOptions
		if args[1] != nil {
			arg1 = args[1].(client.InfoOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Info_Call) Return(systemInfoResult client.SystemInfoResult, err error) *MockClient_Info_Call {
	_c.Call.Return(systemInfoResult, err)
	return _c
}

func (_c *MockClient_Info_Call) RunAndReturn(run func(ctx context.Context, opts client.InfoOptions) (client.SystemInfoResult, error)) *MockClient_Info_Call {
	_c.Call.Return(run)
	return _c
}

// ServerVersion provides a mock function for the type MockClient
func (_mock *MockClient) ServerVersion(ctx context.Context, opts client.ServerVersionOptions) (client.ServerVersionResult, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ServerVersion")
	}

	var r0 client.ServerVersionResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ServerVersionOptions) (client.ServerVersionResult, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ServerVersionOptions) client.ServerVersionResult); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Get(0).(client.ServerVersionResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.ServerVersionOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ServerVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServerVersion'
type MockClient_ServerVersion_Call struct {
	*mock.Call
}

// ServerVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - opts client.ServerVersionOptions
func (_e *MockClient_Expecter) ServerVersion(ctx interface{}, opts interface{}) *MockClient_ServerVersion_Call {
	return &MockClient_ServerVersion_Call{Call: _e.mock.On("ServerVersion", ctx, opts)}
}

func (_c *MockClient_ServerVersion_Call) Run(run func(ctx context.Context, opts client.ServerVersionOptions)) *MockClient_ServerVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.ServerVersionOptions
		if args[1] != nil {
			arg1 = args[1].(client.ServerVersionOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ServerVersion_Call) Return(serverVersionResult client.ServerVersionResult, err error) *MockClient_ServerVersion_Call {
	_c.Call.Return(serverVersionResult, err)
	return _c
}

func (_c *MockClient_ServerVersion_Call) RunAndReturn(run func(ctx context.Context, opts client.ServerVersionOptions) (client.ServerVersionResult, error)) *MockClient_ServerVersion_Call {
	_c.Call.Return(run)
	return _c
}
