// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksystem

import (
	"io"
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCmd creates a new instance of MockCmd. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCmd(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCmd {
	mock := &MockCmd{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCmd is an autogenerated mock type for the Cmd type
type MockCmd struct {
	mock.Mock
}

type MockCmd_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCmd) EXPECT() *MockCmd_Expecter {
	return &MockCmd_Expecter{mock: &_m.Mock}
}

// Kill provides a mock function for the type MockCmd
func (_mock *MockCmd) Kill() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCmd_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type MockCmd_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
func (_e *MockCmd_Expecter) Kill() *MockCmd_Kill_Call {
	return &MockCmd_Kill_Call{Call: _e.mock.On("Kill")}
}

func (_c *MockCmd_Kill_Call) Run(run func()) *MockCmd_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCmd_Kill_Call) Return(err error) *MockCmd_Kill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCmd_Kill_Call) RunAndReturn(run func() error) *MockCmd_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// SetDir provides a mock function for the type MockCmd
func (_mock *MockCmd) SetDir(dir string) {
	_mock.Called(dir)
	return
}

// MockCmd_SetDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDir'
type MockCmd_SetDir_Call struct {
	*mock.Call
}

// SetDir is a helper method to define mock.On call
//   - dir string
func (_e *MockCmd_Expecter) SetDir(dir any) *MockCmd_SetDir_Call {
	return &MockCmd_SetDir_Call{Call: _e.mock.On("SetDir", dir)}
}

func (_c *MockCmd_SetDir_Call) Run(run func(dir string)) *MockCmd_SetDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCmd_SetDir_Call) Return() *MockCmd_SetDir_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCmd_SetDir_Call) RunAndReturn(run func(dir string)) *MockCmd_SetDir_Call {
	_c.Run(run)
	return _c
}

// SetEnv provides a mock function for the type MockCmd
func (_mock *MockCmd) SetEnv(env []string) {
	_mock.Called(env)
	return
}

// MockCmd_SetEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEnv'
type MockCmd_SetEnv_Call struct {
	*mock.Call
}

// SetEnv is a helper method to define mock.On call
//   - env []string
func (_e *MockCmd_Expecter) SetEnv(env any) *MockCmd_SetEnv_Call {
	return &MockCmd_SetEnv_Call{Call: _e.mock.On("SetEnv", env)}
}

func (_c *MockCmd_SetEnv_Call) Run(run func(env []string)) *MockCmd_SetEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCmd_SetEnv_Call) Return() *MockCmd_SetEnv_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCmd_SetEnv_Call) RunAndReturn(run func(env []string)) *MockCmd_SetEnv_Call {
	_c.Run(run)
	return _c
}

// SetStderr provides a mock function for the type MockCmd
func (_mock *MockCmd) SetStderr(w io.Writer) {
	_mock.Called(w)
	return
}

// MockCmd_SetStderr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStderr'
type MockCmd_SetStderr_Call struct {
	*mock.Call
}

// SetStderr is a helper method to define mock.On call
//   - w io.Writer
func (_e *MockCmd_Expecter) SetStderr(w any) *MockCmd_SetStderr_Call {
	return &MockCmd_SetStderr_Call{Call: _e.mock.On("SetStderr", w)}
}

func (_c *MockCmd_SetStderr_Call) Run(run func(w io.Writer)) *MockCmd_SetStderr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCmd_SetStderr_Call) Return() *MockCmd_SetStderr_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCmd_SetStderr_Call) RunAndReturn(run func(w io.Writer)) *MockCmd_SetStderr_Call {
	_c.Run(run)
	return _c
}

// SetStdout provides a mock function for the type MockCmd
func (_mock *MockCmd) SetStdout(w io.Writer) {
	_mock.Called(w)
	return
}

// MockCmd_SetStdout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStdout'
type MockCmd_SetStdout_Call struct {
	*mock.Call
}

// SetStdout is a helper method to define mock.On call
//   - w io.Writer
func (_e *MockCmd_Expecter) SetStdout(w any) *MockCmd_SetStdout_Call {
	return &MockCmd_SetStdout_Call{Call: _e.mock.On("SetStdout", w)}
}

func (_c *MockCmd_SetStdout_Call) Run(run func(w io.Writer)) *MockCmd_SetStdout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCmd_SetStdout_Call) Return() *MockCmd_SetStdout_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCmd_SetStdout_Call) RunAndReturn(run func(w io.Writer)) *MockCmd_SetStdout_Call {
	_c.Run(run)
	return _c
}

// Signal provides a mock function for the type MockCmd
func (_mock *MockCmd) Signal(sig os.Signal) error {
	ret := _mock.Called(sig)

	if len(ret) == 0 {
		panic("no return value specified for Signal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(os.Signal) error); ok {
		r0 = returnFunc(sig)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCmd_Signal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signal'
type MockCmd_Signal_Call struct {
	*mock.Call
}

// Signal is a helper method to define mock.On call
//   - sig os.Signal
func (_e *MockCmd_Expecter) Signal(sig any) *MockCmd_Signal_Call {
	return &MockCmd_Signal_Call{Call: _e.mock.On("Signal", sig)}
}

func (_c *MockCmd_Signal_Call) Run(run func(sig os.Signal)) *MockCmd_Signal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 os.Signal
		if args[0] != nil {
			arg0 = args[0].(os.Signal)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCmd_Signal_Call) Return(err error) *MockCmd_Signal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCmd_Signal_Call) RunAndReturn(run func(sig os.Signal) error) *MockCmd_Signal_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockCmd
func (_mock *MockCmd) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCmd_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockCmd_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockCmd_Expecter) Start() *MockCmd_Start_Call {
	return &MockCmd_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockCmd_Start_Call) Run(run func()) *MockCmd_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCmd_Start_Call) Return(err error) *MockCmd_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCmd_Start_Call) RunAndReturn(run func() error) *MockCmd_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MockCmd
func (_mock *MockCmd) Wait() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCmd_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockCmd_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *MockCmd_Expecter) Wait() *MockCmd_Wait_Call {
	return &MockCmd_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *MockCmd_Wait_Call) Run(run func()) *MockCmd_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCmd_Wait_Call) Return(err error) *MockCmd_Wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCmd_Wait_Call) RunAndReturn(run func() error) *MockCmd_Wait_Call {
	_c.Call.Return(run)
	return _c
}
