// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksystem

import (
	"github.com/openotters/agentfile/agent/system"
	mock "github.com/stretchr/testify/mock"
)

// NewMockExecutor creates a new instance of MockExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutor {
	mock := &MockExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

type MockExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutor) EXPECT() *MockExecutor_Expecter {
	return &MockExecutor_Expecter{mock: &_m.Mock}
}

// Command provides a mock function for the type MockExecutor
func (_mock *MockExecutor) Command(name string, args ...string) system.Cmd {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(name, args)
	} else {
		tmpRet = _mock.Called(name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Command")
	}

	var r0 system.Cmd
	if returnFunc, ok := ret.Get(0).(func(string, ...string) system.Cmd); ok {
		r0 = returnFunc(name, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(system.Cmd)
		}
	}
	return r0
}

// MockExecutor_Command_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Command'
type MockExecutor_Command_Call struct {
	*mock.Call
}

// Command is a helper method to define mock.On call
//   - name string
//   - args ...string
func (_e *MockExecutor_Expecter) Command(name interface{}, args ...interface{}) *MockExecutor_Command_Call {
	return &MockExecutor_Command_Call{Call: _e.mock.On("Command",
		append([]interface{}{name}, args...)...)}
}

func (_c *MockExecutor_Command_Call) Run(run func(name string, args ...string)) *MockExecutor_Command_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockExecutor_Command_Call) Return(cmd system.Cmd) *MockExecutor_Command_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockExecutor_Command_Call) RunAndReturn(run func(name string, args ...string) system.Cmd) *MockExecutor_Command_Call {
	_c.Call.Return(run)
	return _c
}
