// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocksystem

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoopbackAllocator creates a new instance of MockLoopbackAllocator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoopbackAllocator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoopbackAllocator {
	mock := &MockLoopbackAllocator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoopbackAllocator is an autogenerated mock type for the LoopbackAllocator type
type MockLoopbackAllocator struct {
	mock.Mock
}

type MockLoopbackAllocator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoopbackAllocator) EXPECT() *MockLoopbackAllocator_Expecter {
	return &MockLoopbackAllocator_Expecter{mock: &_m.Mock}
}

// Reserve provides a mock function for the type MockLoopbackAllocator
func (_mock *MockLoopbackAllocator) Reserve() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoopbackAllocator_Reserve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reserve'
type MockLoopbackAllocator_Reserve_Call struct {
	*mock.Call
}

// Reserve is a helper method to define mock.On call
func (_e *MockLoopbackAllocator_Expecter) Reserve() *MockLoopbackAllocator_Reserve_Call {
	return &MockLoopbackAllocator_Reserve_Call{Call: _e.mock.On("Reserve")}
}

func (_c *MockLoopbackAllocator_Reserve_Call) Run(run func()) *MockLoopbackAllocator_Reserve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoopbackAllocator_Reserve_Call) Return(s string, err error) *MockLoopbackAllocator_Reserve_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLoopbackAllocator_Reserve_Call) RunAndReturn(run func() (string, error)) *MockLoopbackAllocator_Reserve_Call {
	_c.Call.Return(run)
	return _c
}
