// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentRuntime_Chat_FullMethodName                = "/openotters.agent.v1.AgentRuntime/Chat"
	AgentRuntime_ChatStream_FullMethodName          = "/openotters.agent.v1.AgentRuntime/ChatStream"
	AgentRuntime_PromptObject_FullMethodName        = "/openotters.agent.v1.AgentRuntime/PromptObject"
	AgentRuntime_ListSessions_FullMethodName        = "/openotters.agent.v1.AgentRuntime/ListSessions"
	AgentRuntime_DeleteSession_FullMethodName       = "/openotters.agent.v1.AgentRuntime/DeleteSession"
	AgentRuntime_ListSessionMessages_FullMethodName = "/openotters.agent.v1.AgentRuntime/ListSessionMessages"
	AgentRuntime_ListNotes_FullMethodName           = "/openotters.agent.v1.AgentRuntime/ListNotes"
	AgentRuntime_GetNote_FullMethodName             = "/openotters.agent.v1.AgentRuntime/GetNote"
	AgentRuntime_SaveNote_FullMethodName            = "/openotters.agent.v1.AgentRuntime/SaveNote"
	AgentRuntime_DeleteNote_FullMethodName          = "/openotters.agent.v1.AgentRuntime/DeleteNote"
	AgentRuntime_SetNoteInContext_FullMethodName    = "/openotters.agent.v1.AgentRuntime/SetNoteInContext"
	AgentRuntime_Health_FullMethodName              = "/openotters.agent.v1.AgentRuntime/Health"
	AgentRuntime_Ready_FullMethodName               = "/openotters.agent.v1.AgentRuntime/Ready"
)

// AgentRuntimeClient is the client API for AgentRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentRuntimeClient interface {
	// Chat
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	ChatStream(ctx context.Context, in *ChatStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamEvent], error)
	// Structured output — one-shot, stateless. The runtime hands a
	// user prompt + JSON schema to the underlying LanguageModel via
	// fantasy.GenerateObject; the schema drives whichever native
	// JSON / tool / text mode the provider supports. No session
	// memory, no tool loop.
	PromptObject(ctx context.Context, in *PromptObjectRequest, opts ...grpc.CallOption) (*PromptObjectResponse, error)
	// Sessions
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	ListSessionMessages(ctx context.Context, in *ListSessionMessagesRequest, opts ...grpc.CallOption) (*ListSessionMessagesResponse, error)
	// Notes — per-agent, cross-session KV store the model uses for
	// durable facts (see runtime/pkg/notes). The daemon proxies these
	// for the operator UI; the model itself writes via the note_*
	// tools registered with fantasy.
	ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error)
	GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error)
	SaveNote(ctx context.Context, in *SaveNoteRequest, opts ...grpc.CallOption) (*SaveNoteResponse, error)
	DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error)
	SetNoteInContext(ctx context.Context, in *SetNoteInContextRequest, opts ...grpc.CallOption) (*SetNoteInContextResponse, error)
	// Probes
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Ready(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error)
}

type agentRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentRuntimeClient(cc grpc.ClientConnInterface) AgentRuntimeClient {
	return &agentRuntimeClient{cc}
}

func (c *agentRuntimeClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) ChatStream(ctx context.Context, in *ChatStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatStreamEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentRuntime_ServiceDesc.Streams[0], AgentRuntime_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatStreamRequest, ChatStreamEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntime_ChatStreamClient = grpc.ServerStreamingClient[ChatStreamEvent]

func (c *agentRuntimeClient) PromptObject(ctx context.Context, in *PromptObjectRequest, opts ...grpc.CallOption) (*PromptObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromptObjectResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_PromptObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) ListSessionMessages(ctx context.Context, in *ListSessionMessagesRequest, opts ...grpc.CallOption) (*ListSessionMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionMessagesResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_ListSessionMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotesResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_ListNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNoteResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_GetNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) SaveNote(ctx context.Context, in *SaveNoteRequest, opts ...grpc.CallOption) (*SaveNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveNoteResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_SaveNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNoteResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_DeleteNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) SetNoteInContext(ctx context.Context, in *SetNoteInContextRequest, opts ...grpc.CallOption) (*SetNoteInContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetNoteInContextResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_SetNoteInContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) Ready(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadyResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_Ready_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentRuntimeServer is the server API for AgentRuntime service.
// All implementations must embed UnimplementedAgentRuntimeServer
// for forward compatibility.
type AgentRuntimeServer interface {
	// Chat
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	ChatStream(*ChatStreamRequest, grpc.ServerStreamingServer[ChatStreamEvent]) error
	// Structured output — one-shot, stateless. The runtime hands a
	// user prompt + JSON schema to the underlying LanguageModel via
	// fantasy.GenerateObject; the schema drives whichever native
	// JSON / tool / text mode the provider supports. No session
	// memory, no tool loop.
	PromptObject(context.Context, *PromptObjectRequest) (*PromptObjectResponse, error)
	// Sessions
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	ListSessionMessages(context.Context, *ListSessionMessagesRequest) (*ListSessionMessagesResponse, error)
	// Notes — per-agent, cross-session KV store the model uses for
	// durable facts (see runtime/pkg/notes). The daemon proxies these
	// for the operator UI; the model itself writes via the note_*
	// tools registered with fantasy.
	ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error)
	GetNote(context.Context, *GetNoteRequest) (*GetNoteResponse, error)
	SaveNote(context.Context, *SaveNoteRequest) (*SaveNoteResponse, error)
	DeleteNote(context.Context, *DeleteNoteRequest) (*DeleteNoteResponse, error)
	SetNoteInContext(context.Context, *SetNoteInContextRequest) (*SetNoteInContextResponse, error)
	// Probes
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Ready(context.Context, *ReadyRequest) (*ReadyResponse, error)
	mustEmbedUnimplementedAgentRuntimeServer()
}

// UnimplementedAgentRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentRuntimeServer struct{}

func (UnimplementedAgentRuntimeServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAgentRuntimeServer) ChatStream(*ChatStreamRequest, grpc.ServerStreamingServer[ChatStreamEvent]) error {
	return status.Error(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedAgentRuntimeServer) PromptObject(context.Context, *PromptObjectRequest) (*PromptObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PromptObject not implemented")
}
func (UnimplementedAgentRuntimeServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedAgentRuntimeServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedAgentRuntimeServer) ListSessionMessages(context.Context, *ListSessionMessagesRequest) (*ListSessionMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessionMessages not implemented")
}
func (UnimplementedAgentRuntimeServer) ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotes not implemented")
}
func (UnimplementedAgentRuntimeServer) GetNote(context.Context, *GetNoteRequest) (*GetNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNote not implemented")
}
func (UnimplementedAgentRuntimeServer) SaveNote(context.Context, *SaveNoteRequest) (*SaveNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveNote not implemented")
}
func (UnimplementedAgentRuntimeServer) DeleteNote(context.Context, *DeleteNoteRequest) (*DeleteNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNote not implemented")
}
func (UnimplementedAgentRuntimeServer) SetNoteInContext(context.Context, *SetNoteInContextRequest) (*SetNoteInContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNoteInContext not implemented")
}
func (UnimplementedAgentRuntimeServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAgentRuntimeServer) Ready(context.Context, *ReadyRequest) (*ReadyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ready not implemented")
}
func (UnimplementedAgentRuntimeServer) mustEmbedUnimplementedAgentRuntimeServer() {}
func (UnimplementedAgentRuntimeServer) testEmbeddedByValue()                      {}

// UnsafeAgentRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentRuntimeServer will
// result in compilation errors.
type UnsafeAgentRuntimeServer interface {
	mustEmbedUnimplementedAgentRuntimeServer()
}

func RegisterAgentRuntimeServer(s grpc.ServiceRegistrar, srv AgentRuntimeServer) {
	// If the following call panics, it indicates UnimplementedAgentRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentRuntime_ServiceDesc, srv)
}

func _AgentRuntime_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentRuntimeServer).ChatStream(m, &grpc.GenericServerStream[ChatStreamRequest, ChatStreamEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntime_ChatStreamServer = grpc.ServerStreamingServer[ChatStreamEvent]

func _AgentRuntime_PromptObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).PromptObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_PromptObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).PromptObject(ctx, req.(*PromptObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_ListSessionMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).ListSessionMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_ListSessionMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).ListSessionMessages(ctx, req.(*ListSessionMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_ListNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).ListNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_ListNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).ListNotes(ctx, req.(*ListNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_GetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).GetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_GetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).GetNote(ctx, req.(*GetNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_SaveNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).SaveNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_SaveNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).SaveNote(ctx, req.(*SaveNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_DeleteNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).DeleteNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_DeleteNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).DeleteNote(ctx, req.(*DeleteNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_SetNoteInContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNoteInContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).SetNoteInContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_SetNoteInContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).SetNoteInContext(ctx, req.(*SetNoteInContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_Ready_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).Ready(ctx, req.(*ReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentRuntime_ServiceDesc is the grpc.ServiceDesc for AgentRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openotters.agent.v1.AgentRuntime",
	HandlerType: (*AgentRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _AgentRuntime_Chat_Handler,
		},
		{
			MethodName: "PromptObject",
			Handler:    _AgentRuntime_PromptObject_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _AgentRuntime_ListSessions_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _AgentRuntime_DeleteSession_Handler,
		},
		{
			MethodName: "ListSessionMessages",
			Handler:    _AgentRuntime_ListSessionMessages_Handler,
		},
		{
			MethodName: "ListNotes",
			Handler:    _AgentRuntime_ListNotes_Handler,
		},
		{
			MethodName: "GetNote",
			Handler:    _AgentRuntime_GetNote_Handler,
		},
		{
			MethodName: "SaveNote",
			Handler:    _AgentRuntime_SaveNote_Handler,
		},
		{
			MethodName: "DeleteNote",
			Handler:    _AgentRuntime_DeleteNote_Handler,
		},
		{
			MethodName: "SetNoteInContext",
			Handler:    _AgentRuntime_SetNoteInContext_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _AgentRuntime_Health_Handler,
		},
		{
			MethodName: "Ready",
			Handler:    _AgentRuntime_Ready_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _AgentRuntime_ChatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}
