// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type ChatStreamRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Prompt    string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// When true, the runtime appends the produced parts as a new
	// branch onto the most recent assistant turn for session_id
	// instead of inserting a fresh row. Falls back to insert when
	// no prior assistant turn exists.
	Regenerate    bool `protobuf:"varint,3,opt,name=regenerate,proto3" json:"regenerate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamRequest) Reset() {
	*x = ChatStreamRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamRequest) ProtoMessage() {}

func (x *ChatStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamRequest.ProtoReflect.Descriptor instead.
func (*ChatStreamRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ChatStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatStreamRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ChatStreamRequest) GetRegenerate() bool {
	if x != nil {
		return x.Regenerate
	}
	return false
}

type ChatStreamEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Type    string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Step    int32                  `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	Tool    string                 `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`
	Content string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// tool_id correlates tool.call and tool.result events for the
	// same invocation. Stable for the lifetime of one tool call.
	ToolId string `protobuf:"bytes,5,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	// duration_ms is the wall-clock time the tool spent executing.
	// Populated on tool.result events (and on step.finish where it
	// covers the whole step). Zero on other event types.
	DurationMs    int64 `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamEvent) Reset() {
	*x = ChatStreamEvent{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamEvent) ProtoMessage() {}

func (x *ChatStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamEvent.ProtoReflect.Descriptor instead.
func (*ChatStreamEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ChatStreamEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatStreamEvent) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *ChatStreamEvent) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ChatStreamEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatStreamEvent) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ChatStreamEvent) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type PromptObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plain-text user prompt (single turn; stateless).
	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Raw JSON Schema bytes. Unmarshalled into fantasy/schema.Schema
	// server-side; the common subset (type, properties, required,
	// items, enum, format, min/max) is supported.
	SchemaJson []byte `protobuf:"bytes,2,opt,name=schema_json,json=schemaJson,proto3" json:"schema_json,omitempty"`
	// Optional — surfaces in tool-mode providers as the synthetic
	// tool's name / description. Ignored otherwise.
	SchemaName    string `protobuf:"bytes,3,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	SchemaDesc    string `protobuf:"bytes,4,opt,name=schema_desc,json=schemaDesc,proto3" json:"schema_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptObjectRequest) Reset() {
	*x = PromptObjectRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptObjectRequest) ProtoMessage() {}

func (x *PromptObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptObjectRequest.ProtoReflect.Descriptor instead.
func (*PromptObjectRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PromptObjectRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *PromptObjectRequest) GetSchemaJson() []byte {
	if x != nil {
		return x.SchemaJson
	}
	return nil
}

func (x *PromptObjectRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *PromptObjectRequest) GetSchemaDesc() string {
	if x != nil {
		return x.SchemaDesc
	}
	return ""
}

type PromptObjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Marshalled structured object (valid JSON bytes).
	ObjectJson []byte `protobuf:"bytes,1,opt,name=object_json,json=objectJson,proto3" json:"object_json,omitempty"`
	// The raw assistant text, mostly useful when the model returned
	// repaired or otherwise interesting content alongside the parse.
	RawText       string `protobuf:"bytes,2,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptObjectResponse) Reset() {
	*x = PromptObjectResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptObjectResponse) ProtoMessage() {}

func (x *PromptObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptObjectResponse.ProtoReflect.Descriptor instead.
func (*PromptObjectResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *PromptObjectResponse) GetObjectJson() []byte {
	if x != nil {
		return x.ObjectJson
	}
	return nil
}

func (x *PromptObjectResponse) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *HealthResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x13openotters.agent.v1\"D\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\"*\n" +
	"\fChatResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"j\n" +
	"\x11ChatStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1e\n" +
	"\n" +
	"regenerate\x18\x03 \x01(\bR\n" +
	"regenerate\"\xa1\x01\n" +
	"\x0fChatStreamEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04step\x18\x02 \x01(\x05R\x04step\x12\x12\n" +
	"\x04tool\x18\x03 \x01(\tR\x04tool\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x17\n" +
	"\atool_id\x18\x05 \x01(\tR\x06toolId\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\"\x90\x01\n" +
	"\x13PromptObjectRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1f\n" +
	"\vschema_json\x18\x02 \x01(\fR\n" +
	"schemaJson\x12\x1f\n" +
	"\vschema_name\x18\x03 \x01(\tR\n" +
	"schemaName\x12\x1f\n" +
	"\vschema_desc\x18\x04 \x01(\tR\n" +
	"schemaDesc\"R\n" +
	"\x14PromptObjectResponse\x12\x1f\n" +
	"\vobject_json\x18\x01 \x01(\fR\n" +
	"objectJson\x12\x19\n" +
	"\braw_text\x18\x02 \x01(\tR\arawText\"\x0f\n" +
	"\rHealthRequest\"]\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"\x0e\n" +
	"\fReadyRequest\"%\n" +
	"\rReadyResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready2\xc1\x03\n" +
	"\fAgentRuntime\x12K\n" +
	"\x04Chat\x12 .openotters.agent.v1.ChatRequest\x1a!.openotters.agent.v1.ChatResponse\x12\\\n" +
	"\n" +
	"ChatStream\x12&.openotters.agent.v1.ChatStreamRequest\x1a$.openotters.agent.v1.ChatStreamEvent0\x01\x12c\n" +
	"\fPromptObject\x12(.openotters.agent.v1.PromptObjectRequest\x1a).openotters.agent.v1.PromptObjectResponse\x12Q\n" +
	"\x06Health\x12\".openotters.agent.v1.HealthRequest\x1a#.openotters.agent.v1.HealthResponse\x12N\n" +
	"\x05Ready\x12!.openotters.agent.v1.ReadyRequest\x1a\".openotters.agent.v1.ReadyResponseB9Z7github.com/openotters/agentfile/executor/api/v1;agentv1b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_agent_proto_goTypes = []any{
	(*ChatRequest)(nil),          // 0: openotters.agent.v1.ChatRequest
	(*ChatResponse)(nil),         // 1: openotters.agent.v1.ChatResponse
	(*ChatStreamRequest)(nil),    // 2: openotters.agent.v1.ChatStreamRequest
	(*ChatStreamEvent)(nil),      // 3: openotters.agent.v1.ChatStreamEvent
	(*PromptObjectRequest)(nil),  // 4: openotters.agent.v1.PromptObjectRequest
	(*PromptObjectResponse)(nil), // 5: openotters.agent.v1.PromptObjectResponse
	(*HealthRequest)(nil),        // 6: openotters.agent.v1.HealthRequest
	(*HealthResponse)(nil),       // 7: openotters.agent.v1.HealthResponse
	(*ReadyRequest)(nil),         // 8: openotters.agent.v1.ReadyRequest
	(*ReadyResponse)(nil),        // 9: openotters.agent.v1.ReadyResponse
}
var file_agent_proto_depIdxs = []int32{
	0, // 0: openotters.agent.v1.AgentRuntime.Chat:input_type -> openotters.agent.v1.ChatRequest
	2, // 1: openotters.agent.v1.AgentRuntime.ChatStream:input_type -> openotters.agent.v1.ChatStreamRequest
	4, // 2: openotters.agent.v1.AgentRuntime.PromptObject:input_type -> openotters.agent.v1.PromptObjectRequest
	6, // 3: openotters.agent.v1.AgentRuntime.Health:input_type -> openotters.agent.v1.HealthRequest
	8, // 4: openotters.agent.v1.AgentRuntime.Ready:input_type -> openotters.agent.v1.ReadyRequest
	1, // 5: openotters.agent.v1.AgentRuntime.Chat:output_type -> openotters.agent.v1.ChatResponse
	3, // 6: openotters.agent.v1.AgentRuntime.ChatStream:output_type -> openotters.agent.v1.ChatStreamEvent
	5, // 7: openotters.agent.v1.AgentRuntime.PromptObject:output_type -> openotters.agent.v1.PromptObjectResponse
	7, // 8: openotters.agent.v1.AgentRuntime.Health:output_type -> openotters.agent.v1.HealthResponse
	9, // 9: openotters.agent.v1.AgentRuntime.Ready:output_type -> openotters.agent.v1.ReadyResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
