// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockexecutor

import (
	"context"

	"github.com/openotters/agentfile/executor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockObjectPrompter creates a new instance of MockObjectPrompter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectPrompter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectPrompter {
	mock := &MockObjectPrompter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectPrompter is an autogenerated mock type for the ObjectPrompter type
type MockObjectPrompter struct {
	mock.Mock
}

type MockObjectPrompter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectPrompter) EXPECT() *MockObjectPrompter_Expecter {
	return &MockObjectPrompter_Expecter{mock: &_m.Mock}
}

// PromptObject provides a mock function for the type MockObjectPrompter
func (_mock *MockObjectPrompter) PromptObject(ctx context.Context, req executor.ObjectPromptRequest) ([]byte, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PromptObject")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, executor.ObjectPromptRequest) ([]byte, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, executor.ObjectPromptRequest) []byte); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, executor.ObjectPromptRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectPrompter_PromptObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromptObject'
type MockObjectPrompter_PromptObject_Call struct {
	*mock.Call
}

// PromptObject is a helper method to define mock.On call
//   - ctx context.Context
//   - req executor.ObjectPromptRequest
func (_e *MockObjectPrompter_Expecter) PromptObject(ctx interface{}, req interface{}) *MockObjectPrompter_PromptObject_Call {
	return &MockObjectPrompter_PromptObject_Call{Call: _e.mock.On("PromptObject", ctx, req)}
}

func (_c *MockObjectPrompter_PromptObject_Call) Run(run func(ctx context.Context, req executor.ObjectPromptRequest)) *MockObjectPrompter_PromptObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 executor.ObjectPromptRequest
		if args[1] != nil {
			arg1 = args[1].(executor.ObjectPromptRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectPrompter_PromptObject_Call) Return(bytes []byte, err error) *MockObjectPrompter_PromptObject_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockObjectPrompter_PromptObject_Call) RunAndReturn(run func(ctx context.Context, req executor.ObjectPromptRequest) ([]byte, error)) *MockObjectPrompter_PromptObject_Call {
	_c.Call.Return(run)
	return _c
}
