// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockexecutor

import (
	"context"
	"io"

	"github.com/openotters/agentfile/executor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPrompter creates a new instance of MockPrompter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrompter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrompter {
	mock := &MockPrompter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPrompter is an autogenerated mock type for the Prompter type
type MockPrompter struct {
	mock.Mock
}

type MockPrompter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrompter) EXPECT() *MockPrompter_Expecter {
	return &MockPrompter_Expecter{mock: &_m.Mock}
}

// Prompt provides a mock function for the type MockPrompter
func (_mock *MockPrompter) Prompt(ctx context.Context, req executor.PromptRequest, w io.Writer) error {
	ret := _mock.Called(ctx, req, w)

	if len(ret) == 0 {
		panic("no return value specified for Prompt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, executor.PromptRequest, io.Writer) error); ok {
		r0 = returnFunc(ctx, req, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPrompter_Prompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prompt'
type MockPrompter_Prompt_Call struct {
	*mock.Call
}

// Prompt is a helper method to define mock.On call
//   - ctx context.Context
//   - req executor.PromptRequest
//   - w io.Writer
func (_e *MockPrompter_Expecter) Prompt(ctx interface{}, req interface{}, w interface{}) *MockPrompter_Prompt_Call {
	return &MockPrompter_Prompt_Call{Call: _e.mock.On("Prompt", ctx, req, w)}
}

func (_c *MockPrompter_Prompt_Call) Run(run func(ctx context.Context, req executor.PromptRequest, w io.Writer)) *MockPrompter_Prompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 executor.PromptRequest
		if args[1] != nil {
			arg1 = args[1].(executor.PromptRequest)
		}
		var arg2 io.Writer
		if args[2] != nil {
			arg2 = args[2].(io.Writer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPrompter_Prompt_Call) Return(err error) *MockPrompter_Prompt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPrompter_Prompt_Call) RunAndReturn(run func(ctx context.Context, req executor.PromptRequest, w io.Writer) error) *MockPrompter_Prompt_Call {
	_c.Call.Return(run)
	return _c
}
